### ISSUE TITLE
pypi package not found (sensirion-i2c-sgp4x)

### ISSUE THREAD

**Issue by 1960pghpirates** [Sensirion/python-i2c-sgp4x#1]
On the user manual you provided:
 
https://sensirion.github.io/python-i2c-sgp4x/
 
The installation command is this:
_pip install sensirion-i2c-sgp4x_

This command is not working for me.  I am getting an error saying that the following URL cannot be found:
 
https://pypi.org/simple/sensirion-i2c-sgp4x/
 
When I search on pypi.org for the sensirion-i2c-sgp4x package, I cannot find it.    Can you point me to the package link on pypi.org so that I can install the driver?

**Comment by psachs** [comment]
Hi

Thank you for pointing this out. We haven't published a release yet and therefore you are not able to find the python package on pypi yet. 

I will release a first version immediately so you should be able to install it now from pypi. The URL is correct and should now point to the 0.1.0 release

Best regards,
Pascal
