### ISSUE TITLE
Computing VOC Index with Python

### ISSUE THREAD

**Issue by 1960pghpirates** [Sensirion/python-i2c-sgp4x#2]
After reading through the provided example for SGP40 and the API documentation, I do not know how to extract the VOC Index value.   Everything I could find in the documentation relates to the raw VOC number, not the computed index scale of 1 - 500.   Can you provide an example of how to extract the VOC index value using Python?  The raw value alone is not meaningful to an end user.  Thanks!

**Comment by rnestler** [comment]
Hi @1960pghpirates 
The VOC index value is calculated using the VOC index algorithm: https://github.com/Sensirion/embedded-sgp/blob/master/sgp40_voc_index/sgp40_voc_index.h

We plan to provide a Python package with it as well in the following months.

**Comment by MBjoern** [comment]
Dear @1960pghpirates 

We have just released an updated version of the Gas Index Algorithm to compute Index values from SGP4x raw signal outputs.

We also provide a python_wrapper for the algorithm code and an extensive example usage demonstrating how to use it.

There will be a pip package available soon, with the release of the algorithm, for easy installation. Stay tuned.

Algorithm Repository: https://github.com/Sensirion/gas-index-algorithm
Python Example Usage: https://github.com/Sensirion/gas-index-algorithm/blob/master/python-wrapper/example_sensorbridge.py

I hope this resolves your issue at hand. Please don't hesitate to contact us for further questions and/or feedback.

**Comment by MBjoern** [comment]
@1960pghpirates 

Here's the python package containing the Gas Index Algorithm for easy VOC index computation using Python.

https://pypi.org/project/sensirion-gas-index-algorithm/

Have fun with your project.
